### ISSUE TITLE
Add FAQ entry about overriding the error.mp3

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/azuracast.com#16]
As it's a question I've been asked a few times I think it makes sense to add this to the docs.

Here is an example of what I'd add:

> You can replace the .mp3 file that is playing when there is nothing else playing your station by mounting your own .mp3 file via a `docker-compose.override.yml`. What you have to do there is basically creating a file called `docker-compose.override.yml` in the same directory as your `docker.sh` and `docker-compose.yml` with the following content:
```
version: '2.2'

services:
    stations:
        volumes:
            - /path/to/your/file.mp3:/usr/local/share/icecast/web/error.mp3
```

> You can place your .mp3 file anywhere on your host machine. You just have to specify the path to it by replacing this part: `/path/to/your/file.mp3`
> Your .mp3 file has to be dual channel or you'll encounter a decoding error.
